---
- hosts: mywebservers
  become: yes
  tasks:
   - name: install java on debian nodes(apt-get install xxxxx)
     apt:
       name: "{{myjavapackgeonubuntu}}"
       state: present 
     when: ansible_os_family == "Debian"
   - name: install java on redhat nodes(yum install xxxxx) 
     yum:
       name: "{{myjavapackgeonRedhat}}"
       state: present
     when: ansible_os_family == "RedHat"
